[pacman]
tree
stow
neovim
emacs
bat
dfc
glow
sudo
alacritty
bash
zsh
yay
rsync
zip
awk
sed
git
curl
wget
glances
unzip
unrar
xorg-xmodmap
exa
volumeicon
discord
telegram-desktop
emacs
neovim
gimp
inkscape
firefox
flameshot
rsync
vifm
expac
pcmanfm
transmission-gtk
cmus
youtube-dl
zathura
neofetch
bat
dfc
cmus
cpupower
etcher
ffmpeg
gufw
kdeconnect
newsboat
simple-scan
shellcheck
stow
tree
w3m
vlc
kdeconnect
ttf-mononoki
ttf-roboto-mono
ttf-cascadia-code
fzf
aria2
systemd-swap
binutils
upx
alsa-utils
alsa-plugins
neomutt
i3-gaps
openbox
tint2

qemu
virt-manager
ebtables

xorg-server-xephyr


[yay]
drawio-desktop-bin
