#!/bin/bash

echo "Copying configuration files to git repo..."

cp -r $HOME/.bashrc $HOME/.zshrc $HOME/.tmux.conf $HOME/.vimrc $HOME/GitProjects/configurations-and-scripts/configs/

rm -rf $HOME/GitProjects/configurations-and-scripts/configs/.oh-my-zsh/

cp -r $HOME/.oh-my-zsh/ $HOME/GitProjects/configurations-and-scripts/configs/ 

cp -r $HOME/bin/gitconf $HOME/bin/initscript_solus $HOME/GitProjects/configurations-and-scripts/scripts/

echo "DONE"
