#!/bin/bash

# TRANSFER CONFIG FILES FROM GITLAB REPOSITORY

echo "Checking if git and curl are installed..."
if eopkg check git | awk '{print $5}' | grep -q "OK"; then
    echo "\"git\" is installed!"
else
    sudo eopkg install git
fi

if eopkg check curl | awk '{print $5}' | grep -q "OK"; then
    echo "\"git\" is installed!"
else
    sudo eopkg install curl
fi


echo "Cloning configurations-and-scripts repository to $HOME/GitProjects/"
[ ! -d "$HOME/GitProjects/configurations-and-scripts" ] && git clone https://gitlab.com/risorg/configurations-and-scripts.git $HOME/GitProjects/


echo "Checking and installing all necessary programs..."
if eopkg check tmux | awk '{print $5}' | grep -q "OK"; then
    echo "\"tmux\" is installed!"
else
    sudo eopkg install tmux
fi

if eopkg check zsh | awk '{print $5}' | grep -q "OK"; then
    echo "\"zsh\" is installed!"
else
    sudo eopkg install zsh
fi

if eopkg check vim | awk '{print $5}' | grep -q "OK"; then
    echo "\"vim\" is installed!"
else
    sudo eopkg install vim
fi


echo "Copying files to $HOME ..."
REPO=$HOME/GitProjects/configurations-and-scripts/configs
cp -r $REPO/.bashrc $REPO/.vimrc $REPO/.zshrc $REPO/.tmux.conf $HOME/

[ -d "$HOME/.oh-my-zsh/" ] && rm -rf $HOME/.oh-my-zsh/
cp -r $HOME/GitProjects/configurations-and-scripts/configs/.oh-my-zsh/ $HOME/