#!/usr/bin/env bash

echo FOREGROUND COLORS:
echo -e "  \033[0mNo color foreground"
echo -e "  \033[1;37mWHITE\t\033[0;30mBLACK"
echo -e "  \033[0;34mBLUE\t\033[1;34mLIGHT_BLUE"
echo -e "  \033[0;32mGREEN\t\033[1;32mLIGHT_GREEN"
echo -e "  \033[0;36mCYAN\t\033[1;36mLIGHT_CYAN"
echo -e "  \033[0;31mRED\t\033[1;31mLIGHT_RED"
echo -e "  \033[0;35mPURPLE\t\033[1;35mLIGHT_PURPLE"
echo -e "  \033[0;33mYELLOW\t\033[1;33mLIGHT_YELLOW"
echo -e "  \033[1;30mGRAY\t\033[0;37mLIGHT_GRAY"

echo -e "BACKGROUND COLORS:"
echo -e "\033[1;49m     \t\033[0;100m     "
echo -e "\033[0;40m     \t\033[1;101m     "
echo -e "\033[0;41m     \t\033[1;102m     "
echo -e "\033[0;42m     \t\033[1;103m     "
echo -e "\033[0;43m     \t\033[1;104m     "
echo -e "\033[0;44m     \t\033[1;105m     "
echo -e "\033[0;45m     \t\033[1;106m     "
echo -e "\033[1;46m     \t\033[0;107m     "
