#!/usr/bin/env bash

if [ "$#" -lt 1 ] ; then
    echo -e "Link binaries to \e[1;32m~/.local/bin\e[0m with custom names"
    echo -e "\e[1mUsage:\e[0m \e[4mlinkbin FILE [FILENAME_IN_PATH]\e[0m\n"
    echo -e "\e[1mExample:\e[0m \e[4mlinkbin ~/neovim nvim\e[0m links \e[32m~/.local/bin/nvim\e[0m to \e[32m~/neovim\e[0m"
    echo -e "\e[1mExample:\e[0m \e[4mlinkbin ~/neovim\e[0m links \e[32m~/.local/bin/neovim\e[0m to \e[32m~/neovim\e[0m"
elif [ "$#" -eq 2 ] && [ -f "$HOME/.local/bin/$2" ] ; then
    echo -e "\e[1;31m'$HOME/.local/bin/$2'\e[0m exists! Choose a different filename."
elif [ -f "$1" ] ; then
    if [ ! -x "$1" ] ; then
        echo -e "File \e[1;31m'$1'\e[0m is not executable!"
    elif [ "$#" -eq 1 ]; then
        echo -e "Linking \e[1;32m'$1'\e[0m to \e[1;32m'$HOME/.local/bin/$1'\e[0m"
        ln -s "$(realpath $1)" "$HOME/.local/bin/$1"
    elif [ "$#" -eq 2 ]; then
        echo -e "Linking \e[1;32m'$1'\e[0m to \e[1;32m'$HOME/.local/bin/$2'\e[0m"
        ln -s "$(realpath $1)" "$HOME/.local/bin/$2"
    fi
else
    echo -e "\e[1;31m'$1'\e[0m is not a valid file!"
fi
