#+TITLE: My Emacs Configuration
#+AUTHOR: Dimitris Spythouris
#+OPTIONS: num:nil
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup

* Package Management
** Package Archives
Initialize package.el, add MELPA to the package archives and initialize the package lists.
MELPA gets priority in package searches.
#+BEGIN_SRC emacs-lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)

(setq package-archive-priorities
      '(("melpa-stable" . 20)
        ("gnu" . 10)
        ("melpa" . 0)))

(when (not package-archive-contents)
    (ignore-errors (package-refresh-contents)))
#+END_SRC

** Default Packages
Check if all packages defined in my-packages are installed.
If not, install them. Ensure they exist in the load path.
#+BEGIN_SRC emacs-lisp
(setq my-packages
       '(
        ;; HASKELL
        intero
	haskell-mode
	hindent
	
	;; QOL
	ivy
	swiper
	counsel
	smart-tab
	aggressive-indent
	org-bullets
	htmlize
	treemacs
	treemacs-magit
	doom-modeline
	highlight-indent-guides
	focus
	which-key

	;; WEB DEV
	emmet-mode
	impatient-mode

	;; GIT
	magit
	
	;; THEMES
	darkokai-theme
	ujelly-theme
	atom-one-dark-theme
	))
	  
(dolist (pkg my-packages)
     (unless (package-installed-p pkg)
	    (package-install pkg)))

;; MANUALLY INSTALLED / REQUIRED
(require 'view)
(require 'smart-tab)
#+END_SRC

* Core Setup
** Splash Screen
Skip the splash screen and use a scratch buffer in lisp interaction mode.
#+BEGIN_SRC emacs-lisp
(setq inhibit-splash-screen t
      initial-scratch-message nil
      initial-major-mode 'lisp-interaction-mode)
#+END_SRC

** Bars
Turn off the scroll bar, menu bar and the tool bar.
#+BEGIN_SRC emacs-lisp
(scroll-bar-mode -1)
(tool-bar-mode -1)
(menu-bar-mode -1)
#+END_SRC

** Indentation
Tab width is 2 and tabs are now spaces.
#+BEGIN_SRC emacs-lisp
(setq tab-width 2
      indent-tabs-mode nil)
#+END_SRC

** Backup Files
All backup files are saved in the ~/.saves directory.
#+BEGIN_SRC emacs-lisp
(setq backup-directory-alist `(("." . "~/.saves")))
(setq backup-by-copying t)
#+END_SRC

** Yes/No
When emacs asks for yes/no make it one character.
#+BEGIN_SRC emacs-lisp
(defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC

** Theme

The theme used.
#+BEGIN_SRC emacs-lisp
;;(load-theme 'darkokai t)
(load-theme 'atom-one-dark t)
#+END_SRC

** Font

Font used.
#+BEGIN_SRC emacs-lisp
(set-frame-font "Mononoki 12")
;;(set-frame-font "Iosevka Term SS05 11")
;;(set-frame-font "PT Mono 11")
;;(set-frame-font "Dejavu Sans Mono 11")
#+END_SRC

* Keybindings
** Misc
Miscellaneous keybindings that don't fit into any category.
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-v") 'View-scroll-half-page-forward)
(global-set-key (kbd "M-v") 'View-scroll-half-page-backward)
(global-set-key (kbd "RET") 'newline-and-indent)
(global-set-key (kbd "C-;") 'comment-or-uncomment-region)
(global-set-key (kbd "C-x C-b") 'ibuffer)
(global-set-key (kbd "M-o") 'other-window)
(global-set-key (kbd "<f5>") 'compile)
#+END_SRC

** Org
Use the suggested keybindings from the manual.
#+BEGIN_SRC emacs-lisp
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-cb" 'org-switchb)
#+END_SRC

** Magit
Set git-staus to C-x g
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x g") 'magit-status)
#+END_SRC

** Ivy
Swiper and Counsel bindings for find commands.
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-s") 'swiper)
(global-set-key (kbd "C-x l") 'counsel-locate)
#+END_SRC

* Utilities
** Smart Tab
Uses tab for both indentation and autocompletion as most editors do.
Enable it globally.
#+BEGIN_SRC emacs-lisp
(global-smart-tab-mode 1)
#+END_SRC

** Ivy
Enable Ivy and Counsel.
#+BEGIN_SRC emacs-lisp
(ivy-mode 1)
(counsel-mode 1)
#+END_SRC

Customizations.
#+BEGIN_SRC 
(setq ivy-use-virtual-buffers t)
(setq ivy-count-format "(%d/%d) ")
#+END_SRC

** Which-key
Enable which-key globally.
#+BEGIN_SRC emacs-lisp
(which-key-mode t)
#+END_SRC
** Electric Pair
Auto insert matching pairs of parentheses e.t.c
#+BEGIN_SRC emacs-lisp
(electric-pair-mode 1)
#+END_SRC

** Org
Agenda notes location.
#+BEGIN_SRC emacs-lisp
(setq org-agenda-files '("~/Documents/Nextcloud/Notes/Agenda/"))
#+END_SRC

Add org-habit to the modules list. It is a feature that
offers habit tracking and progress graphs. Tweak the graph size and day
display.
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-modules 'org-habit t)
(setq org-habit-preceding-days 7
      org-habit-following-days 1
      org-habit-graph-column 60
      org-habit-show-habits-only-for-today t)
#+END_SRC

*** Hooks
Enable org bullets.
#+BEGIN_SRC emacs-lisp
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+END_SRC

** Emmet Mode
*** Hooks
Enable emmet on markup and css buffers.
#+BEGIN_SRC emacs-lisp
(add-hook 'sgml-mode-hook 'emmet-mode) ;; Auto-start on any markup modes
(add-hook 'css-mode-hook  'emmet-mode) ;; enable Emmet's css abbreviation.
#+END_SRC
** Highlight Indent Guides
Highlight indentation with characters.
#+BEGIN_SRC emacs-lisp
(setq highlight-indent-guides-method 'character)
#+END_SRC
*** Hooks
Enable highlight indent guides on programming buffers.
#+BEGIN_SRC emacs-lisp
(add-hook 'prog-mode-hook 'highlight-indent-guides-mode)
#+END_SRC

** Flyckeck
*** Hooks
Add ecj to the java mode.
#+BEGIN_SRC emacs-lisp
(add-hook 'java-mode-hook
          (lambda () (setq flycheck-java-ecj-jar-path "/path/to/ecj-4.2.jar")))
#+END_SRC
** Treemacs
Enable various features for treemacs including git support and file tracking.
#+BEGIN_SRC emacs-lisp
(add-hook 'treemacs-mode 'treemacs-follow-mode)
(add-hook 'treemacs-mode 'treemacs-filewatch-mode)
(add-hook 'treemacs-mode 'treemacs-git-mode 'deferred)
;;(treemacs-git-mode 'deferred)
#+END_SRC

** Doom Modeline
Improved modeline.
#+BEGIN_SRC emacs-lisp
(doom-modeline-mode 1)
#+END_SRC

* Programming Languages
** C
*** Hooks
#+BEGIN_SRC emacs-lisp
(add-hook 'c-mode-hook 'flycheck-mode)
(add-hook 'c-mode-hook 'aggressive-indent-mode)
#+END_SRC

** Nim
*** Hooks
Nim suggest mode on nim buffers.
#+BEGIN_SRC emacs-lisp
(add-hook 'nim-mode-hook 'nimsuggest-mode)
#+END_SRC
** Haskell
Enable intero globally.
#+BEGIN_SRC emacs-lisp
(intero-global-mode 1)
#+END_SRC
*** Hooks
Enable intero and indentation modes.
#+BEGIN_SRC emacs-lisp
(add-hook 'haskell-mode-hook 'intero-mode)
(add-hook 'haskell-mode-hook 'haskell-indentation-mode)
(add-hook 'haskell-mode-hook 'hindent-mode)
#+END_SRC

** Emacs Lisp
*** Hooks
#+BEGIN_SRC emacs-lisp
(add-hook 'emacs-lisp-mode-hook 'aggressive-indent-mode)
#+END_SRC

** HTML
*** Hooks
#+BEGIN_SRC emacs-lisp
(add-hook 'html-mode-hook 'aggressive-indent-mode)
#+END_SRC
** Java
*** Hooks
Enable eclim.
#+BEGIN_SRC emacs-lisp
(defun my-java-mode-hook ()
    (eclim-mode t))
#+END_SRC
** CSS
*** Hooks
#+BEGIN_SRC 
(add-hook 'css-mode-hook 'aggressive-indent-mode)
#+END_SRC

** Javascript
*** Hooks
Add js2-mode to javascript buffers and enable eslint with flycheck.
#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
(add-hook 'js-mode 'flycheck-mode)
#+END_SRC
** Clojure
