#+TITLE: My Emacs Configuration
#+AUTHOR: Dimitris Spythouris
#+STARTUP: overview
#+OPTIONS: num:nil

* External dependencies
** LSP
*** Javascript
    - npm i -g javascript-typescript-langserver (lsp completion)
    - npm i -g jshint (flycheck linting)
** Counsel
   - fzf (counsel-fzf)
* Package Management
** Package Archives
   Initialize package.el, add MELPA to the package archives and initialize the package lists.
   MELPA gets priority in package searches.
#+BEGIN_SRC emacs-lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)

(when (not package-archive-contents)
    (ignore-errors (package-refresh-contents)))
#+END_SRC

** Default Packages
   Check if all packages defined in my-packages are installed.
   If not, install them. Ensure they exist in the load path.
#+BEGIN_SRC emacs-lisp
(setq my-packages
  '(
  use-package
  counsel
  ivy
  swiper
  org-bullets
  projectile

  aggressive-indent
  iedit
  quickrun
  alchemist
  eredis

  emmet-mode
  impatient-mode
  yaml-mode
  haskell-mode
  elixir-mode

  yasnippet
  which-key
  htmlize
  treemacs
  treemacs-magit
  treemacs-icons-dired
  treemacs-projectile
  magit
  hindent

  lsp-mode
  lsp-ui
  lsp-ivy
  company-lsp

  moody
  minions
  spacemacs-theme
  gruber-darker-theme
  base16-theme
  ))

(dolist (pkg my-packages)
     (unless (package-installed-p pkg)
      (package-install pkg)))

;; MANUALLY INSTALLED / REQUIRED
(eval-when-compile (require 'use-package))
(require 'view)
(require 'lsp-mode)
(require 'haskell-interactive-mode)
(require 'haskell-process)
#+END_SRC

* Core Setup
** Starting Directory
Configure emacs to start in the home directory
#+BEGIN_SRC emacs-lisp
(setq default-directory "~/")
#+END_SRC

** Scrolling
Smooth scrolling
#+BEGIN_SRC emacs-lisp
(setq mouse-wheel-scroll-amount '(3 ((shift) . 3)))
(setq mouse-wheel-progressive-speed nil)
(setq mouse-wheel-follow-mouse 't)
(setq scroll-step 1)
#+END_SRC
** Splash Screen
   Skip the splash screen and use a scratch buffer in lisp interaction mode.
#+BEGIN_SRC emacs-lisp
   (setq inhibit-splash-screen t
     initial-scratch-message nil
     initial-major-mode 'emacs-lisp-mode)
#+END_SRC

** Bars
   Turn off the scroll bar, menu bar and the tool bar.
#+BEGIN_SRC emacs-lisp
(scroll-bar-mode -1)
(tool-bar-mode -1)
(menu-bar-mode -1)
#+END_SRC

** Indentation
   Tab width is 2 and tabs are now spaces.
#+BEGIN_SRC emacs-lisp
(setq-default indent-tabs-mode nil)
(setq-default tab-width 2)
#+END_SRC

** Backup Files
   All backup files are saved in the ~/.emacs.d/saves directory.
#+BEGIN_SRC emacs-lisp
  (setq backup-directory-alist '(("." . "~/.emacs.d/saves"))
    backup-by-copying t
    version-control t
    delete-old-versions t
    kept-new-versions 20
    kept-old-versions 5
    )
#+END_SRC

** Yes/No
   When emacs asks for yes/no make it one character.
#+BEGIN_SRC emacs-lisp
(defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC

** Theme
   The theme used.
#+BEGIN_SRC emacs-lisp
;;(load-theme 'spacemacs-dark t)
(load-theme 'base16-classic-dark t)
#+END_SRC

** Font

   Font used.
#+BEGIN_SRC emacs-lisp
(add-to-list 'default-frame-alist '(font . "RobotoMono 11" ))
(set-face-attribute 'default nil :family "RobotoMono 11" :height 110 :weight 'normal)
(set-frame-font "RobotoMono 11" nil t)
#+END_SRC

** Essential keybindings
   Miscellaneous global keybindings
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-v") 'View-scroll-half-page-forward)
(global-set-key (kbd "M-v") 'View-scroll-half-page-backward)

(global-set-key (kbd "M-j") (lambda () (interactive) (join-line -1)))

(global-set-key (kbd "RET") 'newline-and-indent)

(global-set-key (kbd "C-x C-b") 'ibuffer)
(global-set-key (kbd "C-c e") 'eshell)
(global-set-key (kbd "M-o") 'other-window)

(global-set-key (kbd "<f5>") 'compile)
(global-set-key (kbd "<C-f9>") 'set-frame-font)

(global-set-key (kbd "S-C-<left>") 'shrink-window-horizontally)
(global-set-key (kbd "S-C-<right>") 'enlarge-window-horizontally)
(global-set-key (kbd "S-C-<down>") 'shrink-window)
(global-set-key (kbd "S-C-<up>") 'enlarge-window)
#+END_SRC

** Org-mode
   Basic org-mode keybindings
#+BEGIN_SRC emacs-lisp
(use-package org
  :bind (("\C-cl" . org-store-link)
         ("\C-ca" . org-agenda)
         ("\C-cc" . org-capture)
         ("\C-cb" . org-switchb)
  ))
#+END_SRC

** Electric pairs
#+BEGIN_SRC emacs-lisp
(electric-pair-mode 1)
#+END_SRC

* External Package Settings
** Ivy, Counsel, Swiper

   Enable ivy globally (replacement for ido).
   Tweak the minibuffer functionality and remove the ^ in filters
#+BEGIN_SRC emacs-lisp
(use-package ivy
  :diminish ivy-mode
  :demand
  :ensure t
  :bind (("C-c C-r" . ivy-resume))
  :config
    (ivy-mode t)
    (setq ivy-initial-inputs-alist nil)
    (setq ivy-use-virtual-buffers t)
    (setq enable-recursive-minibuffers t)
    (setq ivy-count-format "(%d/%d) ")
  )
#+END_SRC

   Enable swiper (enhanced isearch for ivy) and assign C-s to search
#+BEGIN_SRC emacs-lisp
(use-package swiper
  :ensure t
  :bind (("C-s" . swiper))
)
#+END_SRC

   Counsel is a collection of ivy enhanced base commands
   Bind some keys to common commands
#+BEGIN_SRC emacs-lisp
(use-package counsel
  :ensure t
  :demand
  :bind (("M-x" . counsel-M-x)
         ("C-x C-f" . counsel-find-file)
         ("<f2> u" . counsel-unicode-char)
         ("C-c g" . counsel-git)
         ("C-c j" . counsel-git-grep)
         ("C-c k" . counsel-fzf)
         ("C-x l" . counsel-locate)
         ("C-c i" . counsel-imenu)
				 ("<f9>" . counsel-load-theme)
				 ("<f1> x" . counsel-descbinds))
)
#+END_SRC

** Yasnippet
#+BEGIN_SRC emacs-lisp

  (use-package yasnippet
      :ensure t
      :diminish yas-minor-mode
      :config
      (setq yas-snippet-dirs '("~/.emacs.d/snippets"
                               "~/.emacs.d/elpa/yasnippet-snippets-20191117.1730/snippets/"))
      (yas-global-mode)
      :bind
      ("C-M-/"    . company-yasnippet)
      ("C-c <tab>". yas-expand)
)

(yas-snippet-dirs)

#+END_SRC

** Company
   Enable company with various settings
   Add company backends
	 #+BEGIN_SRC emacs-lisp

(use-package company
  :ensure t
  :diminish
  :config
   (setq company-idle-delay 0.3)
   (setq company-minimum-prefix-length 1)
   (setq company-selection-wrap-around t)
   (setq company-tooltip-align-annotations t)
   (setq company-tooltip-limit 10)
   (setq company-dabbrev-downcase nil)
   (company-tng-configure-default)
)

(use-package company-lsp
  :ensure t
  :config
  (add-to-list 'company-backends 'company-lsp)
)

#+END_SRC

** Projectile
#+BEGIN_SRC emacs-lisp
(use-package projectile
  :ensure t
  :config
  (setq projectile-completion-system 'ivy)
  (setq projectile-tags-backend 'etags-select)
  (add-to-list 'projectile-globally-ignored-modes "org-mode")
  (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
  (projectile-mode +1))
#+END_SRC

** Flycheck
   Enable flycheck globally and add M-p, M-n for error navigation
#+BEGIN_SRC emacs-lisp
(use-package flycheck
  :ensure t
  :config
  (add-hook 'after-init-hook 'global-flycheck-mode)
)
#+END_SRC

** Treemacs
#+BEGIN_SRC emacs-lisp
(use-package treemacs
  :ensure t
  :defer t
  :init
  (with-eval-after-load 'winum
    (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
  :config
  (progn
    (setq treemacs-collapse-dirs                 (if treemacs-python-executable 3 0)
          treemacs-deferred-git-apply-delay      0.5
          treemacs-display-in-side-window        t
          treemacs-eldoc-display                 t
          treemacs-file-event-delay              5000
          treemacs-file-follow-delay             0.2
          treemacs-follow-after-init             t
          treemacs-git-command-pipe              ""
          treemacs-goto-tag-strategy             'refetch-index
          treemacs-indentation                   2
          treemacs-indentation-string            " "
          treemacs-is-never-other-window         t
          treemacs-max-git-entries               5000
          treemacs-missing-project-action        'ask
          treemacs-no-png-images                 nil
          treemacs-no-delete-other-windows       t
          treemacs-project-follow-cleanup        nil
          treemacs-persist-file                  (expand-file-name ".cache/treemacs-persist" user-emacs-directory)
          treemacs-position                      'left
          treemacs-recenter-distance             0.1
          treemacs-recenter-after-file-follow    nil
          treemacs-recenter-after-tag-follow     nil
          treemacs-recenter-after-project-jump   'always
          treemacs-recenter-after-project-expand 'on-distance
          treemacs-show-cursor                   nil
          treemacs-show-hidden-files             t
          treemacs-silent-filewatch              nil
          treemacs-silent-refresh                nil
          treemacs-sorting                       'alphabetic-desc
          treemacs-space-between-root-nodes      t
          treemacs-tag-follow-cleanup            t
          treemacs-tag-follow-delay              1.5
          treemacs-width                         30)

    ;; The default width and height of the icons is 22 pixels. If you are
    ;; using a Hi-DPI display, uncomment this to double the icon size.
    ;;(treemacs-resize-icons 44)

    (treemacs-follow-mode t)
    (treemacs-filewatch-mode t)
    (treemacs-fringe-indicator-mode t)
    (pcase (cons (not (null (executable-find "git")))
                 (not (null treemacs-python-executable)))
      (`(t . t)
       (treemacs-git-mode 'deferred))
      (`(t . _)
       (treemacs-git-mode 'simple))))
  :bind
  (:map global-map
        ("M-0"       . treemacs-select-window)
        ("C-x t 1"   . treemacs-delete-other-windows)
        ("C-x t t"   . treemacs)
        ("C-x t B"   . treemacs-bookmark)
        ("C-x t C-t" . treemacs-find-file)
        ("C-x t M-t" . treemacs-find-tag)))
        

(use-package treemacs-projectile
  :after treemacs projectile
  :ensure t)

(use-package treemacs-icons-dired
  :after treemacs dired
  :ensure t
  :config (treemacs-icons-dired-mode))

(use-package treemacs-magit
  :after treemacs magit
  :ensure t)

#+END_SRC

** Which-key
   Which-key is a keybinding preview utility to show all subsequent keys when waiting for commands.
#+BEGIN_SRC emacs-lisp
(use-package which-key
  :ensure t
  :diminish which-key-mode
  :config
    (which-key-mode t)
)
#+END_SRC

** Iedit
#+BEGIN_SRC emacs-lisp
(use-package iedit
  :ensure t
	:bind ("C-;" . iedit-mode)
)
#+END_SRC

** Magit
   Magit is an interface to git
   Access it with C-x g
#+BEGIN_SRC emacs-lisp
(use-package magit
  :ensure t
  :bind ("C-x g". magit-status)
)
#+END_SRC

** Org Bullets
#+BEGIN_SRC emacs-lisp
(use-package org-bullets
    :hook (org-mode . org-bullets-mode))
#+END_SRC
** Quickrun
   Quickrun provides utilities to quickly compile and execute programs
   F6 runs a program in eshell
#+BEGIN_SRC emacs-lisp
(use-package quickrun
  :ensure t
  :bind ("<f6>" . quickrun-shell)
)
#+END_SRC

** LSP
   Emacs Language Server Protocol support
   Enable it on certain languages along with most of it's addons
#+BEGIN_SRC emacs-lisp
(use-package lsp-mode
  :hook ((c-mode . lsp)
         (rust-mode . lsp))
  :commands lsp
)

;; optionally
(use-package lsp-ui :commands lsp-ui-mode)
(use-package company-lsp :commands company-lsp)
(use-package lsp-treemacs :commands lsp-treemacs-errors-list)
#+END_SRC

** Emmet
   Offers snippets for html and css
#+BEGIN_SRC emacs-lisp
(use-package emmet-mode
  :ensure t
  :hook ((sgml-mode . emmet-mode)
         (css-mode . emmet-mode))
)
#+END_SRC

** Haskell-mode
#+BEGIN_SRC emacs-lisp
(use-package haskell-mode
  :ensure t
  :bind (:map haskell-mode-map
        ("<f8>"    . haskell-navigate-imports)
        ("C-c C-c" . haskell-compile)
        ("C-c C-l" . haskell-process-load-or-reload)
        ("C-`"     . haskell-interactive-bring)
        ("C-c C-t" . haskell-process-do-type)
        ("C-c C-i" . haskell-process-do-info)
        ("C-c C-k" . haskell-interactive-mode-clear))
  :config
  (setq haskell-interactive-popup-errors nil)
  (setq haskell-process-suggest-remove-import-lines t)
  (setq haskell-process-auto-import-loaded-modules t)
  (setq haskell-process-log t)
  (setq haskell-compile-cabal-build-command "stack build")
  (setq haskell-process-suggest-hoogle-imports t)
  :hook
  ((haskell-mode . haskell-indentation-mode)
   (haskell-mode . interactive-haskell-mode)
   (haskell-mode . company-mode)
   (haskell-mode . hindent-mode)
   (haskell-mode .
          (lambda ()
            (set (make-local-variable 'company-backends)
                 (append '((company-capf company-dabbrev-code))
                         company-backends))
            (setq flymake-no-changes-timeout nil)
            (setq flymake-start-syntax-check-on-newline nil)
            (setq flycheck-check-syntax-automatically '(save mode-enabled))))))
#+END_SRC

** Moody + Minions
   Enable Moody and Minions
#+BEGIN_SRC emacs-lisp
(use-package moody
  :config
  (column-number-mode t)
  (setq x-underline-at-descent-line t)
  (moody-replace-mode-line-buffer-identification)
  (moody-replace-vc-mode))

(use-package minions
  :config (minions-mode t))
#+END_SRC

* Programming Language Settings
** C
   Tab = 4 spaces, bsd indentation style
#+BEGIN_SRC emacs-lisp
(setq-default c-basic-offset 4)
(setq-default c-default-style "bsd")
#+END_SRC

*** Hooks
#+BEGIN_SRC emacs-lisp
(add-hook 'c-mode-hook 'flycheck-mode)
(add-hook 'c-mode-hook 'company-mode)
;;(add-hook 'c-mode-hook 'aggressive-indent-mode)
(add-hook 'c-mode-hook #'lsp)
#+END_SRC

** HTML
*** Hooks
#+BEGIN_SRC emacs-lisp
(add-hook 'html-mode-hook 'aggressive-indent-mode)
#+END_SRC

** CSS
*** Hooks
#+BEGIN_SRC emacs-lisp
(add-hook 'css-mode-hook 'aggressive-indent-mode)
(add-hook 'css-mode-hook 'company-mode)
#+END_SRC

** Javascript
*** Hooks
    Add js2-mode to javascript buffers and enable eslint with flycheck.
#+BEGIN_SRC emacs-lisp
(add-hook 'js-mode-hook 'company-mode)
(add-hook 'js-mode-hook 'flycheck-mode)
(add-hook 'js-mode-hook #'lsp)
#+END_SRC


    p
* My functions
  Indent the whole buffer
#+BEGIN_SRC emacs-lisp
(defun iwb ()
  "indent whole buffer"
  (interactive)
  (delete-trailing-whitespace)
  (indent-region (point-min) (point-max) nil)
  (untabify (point-min) (point-max))
)
#+END_SRC

